# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Google Play"
  lane :deploy do
    # Decode the base64-encoded JSON key stored in the environment variable
    require 'base64'
    json_key_base64  = ENV['SERVICE_ACCOUNT_JSON']
    json_key_data = Base64.decode64(json_key_base64)

    supply(
          json_key_data: File.read(json_key_data),
          package_name: "com.app.moviematrix",
          apk: "./app/build/outputs/apk/release/app-release.apk"
        )
  end
end
