name: Android CI/CD

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload Test Report
      if: failure() || success()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: app/build/reports/tests/testDebugUnitTest

    - name: Decrypt and Set up Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      shell: pwsh
      run: |
        $DecodedBytes = [System.Convert]::FromBase64String($env:KEYSTORE_BASE64)
        [System.IO.File]::WriteAllBytes('moviematrix.jks', $DecodedBytes)
        Write-Host "Keystore file created:"
        Get-Item moviematrix.jks

    - name: Verify Decrypted Keystore
      env:
       KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      shell: pwsh
      run: |
        keytool -list -keystore moviematrix.jks -storepass $env:KEYSTORE_PASSWORD
        
    - name: Decrypt Service Account JSON
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      shell: pwsh
      run: |
        $DecodedJsonBytes = [System.Convert]::FromBase64String($env:SERVICE_ACCOUNT_JSON)
        [System.IO.File]::WriteAllBytes('movie-matrix.json', $DecodedJsonBytes)
        Write-Host "Service Account JSON created:"
        Get-Item movie-matrix.json

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      env:
        JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\17.0.11-9\x64
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: |
        echo "Signing APK with alias: $env:KEY_ALIAS"
        jarsigner -verbose -keystore moviematrix.jks -storepass $env:KEYSTORE_PASSWORD -keypass $env:KEY_PASSWORD -signedjar app-release.apk app/build/outputs/apk/release/app-release-unsigned.apk $env:KEY_ALIAS
        
    # - name: Align APK
    #   run: |
    #     zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

    - name: Set up Android SDK
      shell: pwsh
      run: |
       $ANDROID_SDK_ROOT = "$env:RUNNER_TEMP\android-sdk"
        New-Item -ItemType Directory -Path $ANDROID_SDK_ROOT
        curl -o android-sdk.zip https://dl.google.com/android/repository/commandlinetools-win-8092744_latest.zip
        Expand-Archive -Path android-sdk.zip -DestinationPath $ANDROID_SDK_ROOT
        Move-Item -Path "$ANDROID_SDK_ROOT\cmdline-tools" -Destination "$ANDROID_SDK_ROOT\cmdline-tools-latest"
        New-Item -ItemType Directory -Path "$ANDROID_SDK_ROOT\cmdline-tools"
        Move-Item -Path "$ANDROID_SDK_ROOT\cmdline-tools-latest" -Destination "$ANDROID_SDK_ROOT\cmdline-tools\latest"
        $env:PATH += ";$ANDROID_SDK_ROOT\cmdline-tools\latest\bin;$ANDROID_SDK_ROOT\platform-tools"
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-31" "build-tools;31.0.0"
    
    - name: Verify APK
      run: |
        apksigner verify app/build/outputs/apk/release/app-release.apk
      shell: pwsh
      env:
        PATH: ${{ env.PATH }};$ANDROID_SDK_ROOT\build-tools\31.0.0

    - name: Upload Signed APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Install Fastlane
      run: gem install fastlane

    - name: Deploy to Google Play
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        echo $SERVICE_ACCOUNT_JSON | base64 --decode > movie-matrix.json
        bundle exec fastlane android deploy
