name: Android CI/CD

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload Test Report
      if: failure() || success()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: app/build/reports/tests/testDebugUnitTest

    - name: Decrypt and Set up Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      shell: pwsh
      run: |
        $DecodedBytes = [System.Convert]::FromBase64String($env:KEYSTORE_BASE64)
        [System.IO.File]::WriteAllBytes('moviematrix.jks', $DecodedBytes)
        Write-Host "Keystore file created:"
        Get-Item moviematrix.jks

    - name: Verify Decrypted Keystore
      run: |
        keytool -list -keystore moviematrix.jks -storepass $env:KEYSTORE_PASSWORD
        
    - name: Decrypt Service Account JSON
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      shell: pwsh
      run: |
        $DecodedJsonBytes = [System.Convert]::FromBase64String($env:SERVICE_ACCOUNT_JSON)
        [System.IO.File]::WriteAllBytes('movie-matrix.json', $DecodedJsonBytes)
        Write-Host "Service Account JSON created:"
        Get-Item movie-matrix.json

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      env:
        JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\17.0.11-9\x64
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: |
        echo "Signing APK with alias: $env:KEY_ALIAS"
        jarsigner -verbose -keystore moviematrix.jks -storepass $env:KEYSTORE_PASSWORD -keypass $env:KEY_PASSWORD -signedjar app-release.apk app/build/outputs/apk/release/app-release-unsigned.apk $env:KEY_ALIAS
        
    - name: Align APK
      run: |
        zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

    - name: Verify APK
      run: |
        apksigner verify app/build/outputs/apk/release/app-release.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Install Fastlane
      run: gem install fastlane

    - name: Deploy to Google Play
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        echo $SERVICE_ACCOUNT_JSON | base64 --decode > movie-matrix.json
        bundle exec fastlane android deploy
